{
  "host": "0.0.0.0",
  "model": "/workspace/volume/data/GLM-5.3-BF16-W4A8",
  "served-model-name": "glm-5.3",
  "tokenizer-mode": "auto",
  "quantization": "smoothquant",
  "trust-remote-code": true,
  "distributed-executor-backend": "mp",
  "tensor-parallel-size": 8,
  "data-parallel-size": 1,
  "enable-expert-parallel": true,
  "block-size": 16,
  "gpu-memory-utilization": 0.93,
  "no-enable-prefix-caching": true,
  "enable-chunked-prefill": true,
  "enable-prompt-tokens-details": true,
  "enable-auto-tool-choice": true,
  "tool-call-parser": "glm47",
  "reasoning-parser": "glm45",
  "enforce-eager": true,
  "max-num-seqs": 8,
  "additional-config": "{\"dispatch_shared_expert_parallel\": true}",
  "port": 8100,
  "max-model-len": 262144,
  "max-num-batched-tokens": 8192,
  "kv-transfer-config": "{\"kv_connector\": \"NixlConnector\", \"kv_role\": \"kv_producer\", \"kv_load_failure_policy\": \"fail\"}"
}
